# POST http://localhost:3000/movies
# Content-Type: application/json

# {
    
#     "name": "test",
#     "year": 2024
# }

PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    
    "title": "patch",
    "year": 2024
}